addSbtPlugin("org.scalameta"  % "sbt-scalafmt"       % "2.5.5")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"       % "0.14.3")
addSbtPlugin("org.typelevel"  % "sbt-tpolecat"       % "0.5.2")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"      % "0.13.1")
addSbtPlugin("com.github.sbt" % "sbt-github-actions" % "0.25.0")
addSbtPlugin("org.typelevel"  % "sbt-fs2-grpc"       % "2.8.2")
addSbtPlugin("com.github.sbt" % "sbt-javaagent"      % "0.1.8")
